"""empty message

Revision ID: ce739a7f9066
Revises: 
Create Date: 2021-09-22 14:46:56.501736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce739a7f9066'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symbol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=50), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('country', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_ticker'), 'symbol', ['ticker'], unique=False)
    op.create_table('symbol_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('date_create', sa.DateTime(), nullable=True),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('p_e', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('p_s', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('p_b', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('p_cash', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('p_free_cash', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('dividend_yield', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('e_p_s', sa.DECIMAL(scale=2), nullable=True),
    sa.Column('shares_outstanding', sa.Integer(), nullable=True),
    sa.Column('shares_float', sa.Integer(), nullable=True),
    sa.Column('insider_ownership', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('institutional_ownership', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('float_short', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('short_ratio', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('return_on_equity', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('long_term_debt_to_equity', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('total_debt_to_equity', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('gross_margin', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('operating_margin', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('average_volume', sa.Integer(), nullable=True),
    sa.Column('relative_volume', sa.DECIMAL(precision=7, scale=2), nullable=True),
    sa.Column('price', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('change', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('price_and_volume', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_symbol_stats_average_volume'), 'symbol_stats', ['average_volume'], unique=False)
    op.create_index(op.f('ix_symbol_stats_date_create'), 'symbol_stats', ['date_create'], unique=False)
    op.create_index(op.f('ix_symbol_stats_market_cap'), 'symbol_stats', ['market_cap'], unique=False)
    op.create_index(op.f('ix_symbol_stats_price'), 'symbol_stats', ['price'], unique=False)
    op.create_index(op.f('ix_symbol_stats_price_and_volume'), 'symbol_stats', ['price_and_volume'], unique=False)
    op.create_index(op.f('ix_symbol_stats_volume'), 'symbol_stats', ['volume'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_symbol_stats_volume'), table_name='symbol_stats')
    op.drop_index(op.f('ix_symbol_stats_price_and_volume'), table_name='symbol_stats')
    op.drop_index(op.f('ix_symbol_stats_price'), table_name='symbol_stats')
    op.drop_index(op.f('ix_symbol_stats_market_cap'), table_name='symbol_stats')
    op.drop_index(op.f('ix_symbol_stats_date_create'), table_name='symbol_stats')
    op.drop_index(op.f('ix_symbol_stats_average_volume'), table_name='symbol_stats')
    op.drop_table('symbol_stats')
    op.drop_index(op.f('ix_symbol_ticker'), table_name='symbol')
    op.drop_table('symbol')
    # ### end Alembic commands ###
